### ISSUE TITLE
Ability to receive text files programatically

### ISSUE THREAD

**Issue by jgorset** [schibsted/WAAS#68]
Since WAAS can be used as a service as well as a website, it'd be useful if there was a way to receive the text file back other than e-mail. A way that is easier to integrate with programatically, like a webhook, for example?

**Comment by anderser** [comment]
Started some work here. In progress: https://github.com/anderser/WAAS/tree/webhook

**Comment by anderser** [comment]
PR here https://github.com/schibsted/WAAS/pull/95

**Comment by jgorset** [comment]
Awesome!

**Comment by Johannes-Andersen** [comment]
Webhooks are now possible. So closing this :)
