### ISSUE TITLE
Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)

### ISSUE THREAD

**Issue by orjanv** [schibsted/WAAS#94]
I'm running this on a laptop with 8GB RAM and get this message when uploading a minute long mp3 file of ~300kb size. The docker stats confirm that the worker goes up in memory use. Is there anything to be done with this, make is spend more time, or how much RAM is required to run this?

**Comment by Johannes-Andersen** [comment]
Hey, the vram requirements would be the same as noted in the README in the open AI repo
https://github.com/openai/whisper#available-models-and-languages

![C56D8223-4BEF-4BA4-B4BB-5D221817CB3A](https://user-images.githubusercontent.com/57638117/216259920-eb33cdbc-1572-482b-8683-170dcd3841e2.jpeg)

When I have been developing locally it’s been working fine for me using the tiny model on a M1 MacBook Pro

**Comment by orjanv** [comment]
This worked, the issue can be closed.

**Comment by johncadengo** [comment]
@orjanv I'm running into a similar issue, however, I have 2 GPUs with 8GB vram each. Is it possible to split the workload between the 2 GPUs? 

Otherwise, is it possible to disable the large model in the web UI and only show the Medium and model and lower?

**Comment by johncadengo** [comment]
@Johannes-Andersen I'm running into a similar issue, however, I have 2 GPUs with 8GB vram each. Is it possible to split the workload between the 2 GPUs? 

Otherwise, is it possible to disable the large model in the web UI and only show the Medium and model and lower?
